apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: urlfeederservice-rs
  labels:
    name: urlfeederservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlfeederservice-app
  template:
    metadata:
      labels:
        app: urlfeederservice-app
    spec:
      containers:
        - name: urlfeederservice
          image: srivyshnavik/urlfeederservice:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      imagePullSecrets:
        - name:  docker-hub-secret