# version: "3"
# services:
#   zookeeper:
#     image: zookeeper
#     # network_mode: bridge
#     container_name: zookeeper
#     ports:
#       - "2181:2181"
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     image: wurstmeister/kafka
#     network_mode: bridge
#     container_name: kafka
#     ports:
#       - "9092:9092"
#     environment:
#       # HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $$1}'"
#       KAFKA_BROKER_ID: 1
#       KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9092
#       KAFKA_ZOOKEEPER_CONNECT: localhost:2181
#       ALLOW_PLAINTEXT_LISTENERS: yes
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       # KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181
#       # KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
#       # - KAFKA_BROKER_ID=1
#     depends_on:
#       - zookeeper

version: "3"
services:
  zookeeper:
    image: zookeeper
    # network_mode: bridge
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: wurstmeister/kafka
    # network_mode: bridge
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $$1}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,172.18.0.3:9092
      ALLOW_PLAINTEXT_LISTENERS: yes
    depends_on:
      - zookeeper